export type TemplateCategory = 'flyer' | 'logo' | 'certificate' | 'social';

export interface Template {
  id: string;
  name: string;
  category: TemplateCategory;
  width: number;
  height: number;
  thumbnail: string; // CSS gradient or color for preview
  objects: object[];
  background: string;
}

export const TEMPLATES: Template[] = [
  // ─────────────── FLYERS ───────────────
  {
    id: 'flyer-event',
    name: 'Event Night',
    category: 'flyer',
    width: 600,
    height: 800,
    thumbnail: 'linear-gradient(135deg, #1a0533 0%, #4f1a8a 50%, #e040fb 100%)',
    background: '#1a0533',
    objects: [
      {
        type: 'rect',
        left: 0, top: 0, width: 600, height: 800,
        fill: 'linear-gradient(135deg, #1a0533, #4f1a8a)',
        selectable: false, evented: false, excludeFromExport: true,
      },
      {
        type: 'rect',
        left: 40, top: 40, width: 520, height: 720,
        fill: 'transparent',
        stroke: 'rgba(224,64,251,0.4)', strokeWidth: 2,
        rx: 4, ry: 4,
        selectable: false, evented: false,
      },
      {
        type: 'text',
        text: 'FRIDAY\nNIGHT',
        left: 80, top: 200,
        fontFamily: 'Impact',
        fontSize: 92,
        fontWeight: 'bold',
        fill: '#ffffff',
        lineHeight: 0.9,
        charSpacing: -20,
      },
      {
        type: 'text',
        text: 'EXCLUSIVE PARTY',
        left: 80, top: 410,
        fontFamily: 'Arial',
        fontSize: 18,
        fontWeight: '300',
        fill: '#e040fb',
        charSpacing: 80,
      },
      {
        type: 'line',
        x1: 80, y1: 445, x2: 300, y2: 445,
        stroke: 'rgba(224,64,251,0.5)', strokeWidth: 1,
      },
      {
        type: 'text',
        text: 'SATURDAY, JUNE 15, 2025',
        left: 80, top: 460,
        fontFamily: 'Arial',
        fontSize: 14,
        fill: 'rgba(255,255,255,0.7)',
        charSpacing: 40,
      },
      {
        type: 'text',
        text: 'THE GRAND VENUE • 9PM ONWARDS',
        left: 80, top: 485,
        fontFamily: 'Arial',
        fontSize: 13,
        fill: 'rgba(255,255,255,0.5)',
        charSpacing: 20,
      },
      {
        type: 'text',
        text: 'TICKETS: $25',
        left: 80, top: 700,
        fontFamily: 'Arial',
        fontSize: 16,
        fontWeight: 'bold',
        fill: '#e040fb',
        charSpacing: 40,
      },
    ],
  },
  {
    id: 'flyer-sale',
    name: 'Big Sale',
    category: 'flyer',
    width: 600,
    height: 800,
    thumbnail: 'linear-gradient(135deg, #ff6b35 0%, #f7c59f 100%)',
    background: '#fff5ee',
    objects: [
      {
        type: 'rect',
        left: 0, top: 0, width: 600, height: 800,
        fill: '#fff5ee',
        selectable: false, evented: false,
      },
      {
        type: 'rect',
        left: 0, top: 0, width: 600, height: 300,
        fill: '#ff6b35',
        selectable: false, evented: false,
      },
      {
        type: 'text',
        text: 'MEGA\nSALE',
        left: 300, top: 60,
        originX: 'center',
        fontFamily: 'Impact',
        fontSize: 110,
        fill: '#ffffff',
        lineHeight: 0.85,
        textAlign: 'center',
      },
      {
        type: 'text',
        text: 'UP TO 70% OFF',
        left: 300, top: 330,
        originX: 'center',
        fontFamily: 'Arial',
        fontSize: 28,
        fontWeight: 'bold',
        fill: '#ff6b35',
        charSpacing: 60,
        textAlign: 'center',
      },
      {
        type: 'text',
        text: 'ON SELECTED ITEMS',
        left: 300, top: 370,
        originX: 'center',
        fontFamily: 'Arial',
        fontSize: 14,
        fill: '#888',
        charSpacing: 40,
        textAlign: 'center',
      },
      {
        type: 'text',
        text: 'Limited time offer. While stocks last.',
        left: 300, top: 700,
        originX: 'center',
        fontFamily: 'Arial',
        fontSize: 13,
        fill: '#999',
        textAlign: 'center',
      },
    ],
  },
  {
    id: 'flyer-food',
    name: 'Restaurant Menu',
    category: 'flyer',
    width: 600,
    height: 800,
    thumbnail: 'linear-gradient(135deg, #1b2a1b 0%, #2d5016 50%, #4a7c2d 100%)',
    background: '#1b2a1b',
    objects: [
      {
        type: 'rect',
        left: 0, top: 0, width: 600, height: 800,
        fill: '#1b2a1b',
        selectable: false, evented: false,
      },
      {
        type: 'text',
        text: '🌿',
        left: 300, top: 60,
        originX: 'center',
        fontSize: 48,
        textAlign: 'center',
      },
      {
        type: 'text',
        text: 'VERDE',
        left: 300, top: 130,
        originX: 'center',
        fontFamily: 'Georgia',
        fontSize: 72,
        fill: '#c8e6a0',
        charSpacing: 120,
        textAlign: 'center',
        fontStyle: 'italic',
      },
      {
        type: 'text',
        text: 'KITCHEN & BAR',
        left: 300, top: 210,
        originX: 'center',
        fontFamily: 'Arial',
        fontSize: 13,
        fill: '#7a9e5a',
        charSpacing: 80,
        textAlign: 'center',
      },
      {
        type: 'line',
        x1: 160, y1: 250, x2: 440, y2: 250,
        stroke: 'rgba(200,230,160,0.2)', strokeWidth: 1,
      },
      {
        type: 'text',
        text: 'SEASONAL MENU',
        left: 300, top: 280,
        originX: 'center',
        fontFamily: 'Arial',
        fontSize: 11,
        fill: '#7a9e5a',
        charSpacing: 60,
        textAlign: 'center',
      },
      {
        type: 'text',
        text: 'Grilled Salmon   $28\nRisotto Verde   $22\nChef\'s Steak   $38\nVegan Bowl   $18',
        left: 120, top: 340,
        fontFamily: 'Georgia',
        fontSize: 18,
        fill: '#c8e6a0',
        lineHeight: 2,
      },
      {
        type: 'text',
        text: 'Reservations: (555) 234-5678',
        left: 300, top: 720,
        originX: 'center',
        fontFamily: 'Arial',
        fontSize: 13,
        fill: '#7a9e5a',
        textAlign: 'center',
      },
    ],
  },

  // ─────────────── LOGOS ───────────────
  {
    id: 'logo-modern',
    name: 'Modern Tech',
    category: 'logo',
    width: 500,
    height: 300,
    thumbnail: 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)',
    background: '#0f172a',
    objects: [
      {
        type: 'rect',
        left: 0, top: 0, width: 500, height: 300,
        fill: '#0f172a',
        selectable: false, evented: false,
      },
      {
        type: 'rect',
        left: 160, top: 110, width: 44, height: 44,
        fill: '#6366f1',
        rx: 10, ry: 10,
        angle: 15,
      },
      {
        type: 'rect',
        left: 196, top: 126, width: 44, height: 44,
        fill: '#818cf8',
        rx: 10, ry: 10,
        angle: 15,
        opacity: 0.7,
      },
      {
        type: 'text',
        text: 'NEXUS',
        left: 260, top: 118,
        fontFamily: 'Impact',
        fontSize: 44,
        fill: '#ffffff',
        charSpacing: 60,
      },
      {
        type: 'text',
        text: 'TECHNOLOGY',
        left: 260, top: 172,
        fontFamily: 'Arial',
        fontSize: 12,
        fill: '#6366f1',
        charSpacing: 120,
        fontWeight: '600',
      },
    ],
  },
  {
    id: 'logo-minimal',
    name: 'Minimal Badge',
    category: 'logo',
    width: 500,
    height: 300,
    thumbnail: 'linear-gradient(135deg, #fafafa 0%, #f0f0f0 100%)',
    background: '#ffffff',
    objects: [
      {
        type: 'rect',
        left: 0, top: 0, width: 500, height: 300,
        fill: '#ffffff',
        selectable: false, evented: false,
      },
      {
        type: 'circle',
        left: 190, top: 100, radius: 50,
        fill: 'transparent',
        stroke: '#111', strokeWidth: 3,
      },
      {
        type: 'text',
        text: 'A',
        left: 239, top: 122,
        originX: 'center',
        fontFamily: 'Georgia',
        fontSize: 42,
        fill: '#111',
        fontStyle: 'italic',
        fontWeight: 'bold',
      },
      {
        type: 'text',
        text: 'ARCADIA',
        left: 262, top: 126,
        fontFamily: 'Arial',
        fontSize: 28,
        fill: '#111',
        charSpacing: 40,
        fontWeight: '300',
      },
      {
        type: 'text',
        text: 'DESIGN STUDIO',
        left: 262, top: 165,
        fontFamily: 'Arial',
        fontSize: 11,
        fill: '#888',
        charSpacing: 80,
      },
    ],
  },
  {
    id: 'logo-bold',
    name: 'Bold Brand',
    category: 'logo',
    width: 500,
    height: 300,
    thumbnail: 'linear-gradient(135deg, #dc2626 0%, #991b1b 100%)',
    background: '#dc2626',
    objects: [
      {
        type: 'rect',
        left: 0, top: 0, width: 500, height: 300,
        fill: '#dc2626',
        selectable: false, evented: false,
      },
      {
        type: 'text',
        text: 'BLAZE',
        left: 250, top: 90,
        originX: 'center',
        fontFamily: 'Impact',
        fontSize: 90,
        fill: '#ffffff',
        charSpacing: 40,
        textAlign: 'center',
      },
      {
        type: 'rect',
        left: 80, top: 196, width: 340, height: 3,
        fill: 'rgba(255,255,255,0.4)',
      },
      {
        type: 'text',
        text: 'APPAREL CO.',
        left: 250, top: 208,
        originX: 'center',
        fontFamily: 'Arial',
        fontSize: 14,
        fill: 'rgba(255,255,255,0.8)',
        charSpacing: 100,
        textAlign: 'center',
        fontWeight: '300',
      },
    ],
  },

  // ─────────────── CERTIFICATES ───────────────
  {
    id: 'cert-achievement',
    name: 'Achievement',
    category: 'certificate',
    width: 800,
    height: 560,
    thumbnail: 'linear-gradient(135deg, #fef3c7 0%, #fde68a 50%, #fbbf24 100%)',
    background: '#fffbeb',
    objects: [
      {
        type: 'rect',
        left: 0, top: 0, width: 800, height: 560,
        fill: '#fffbeb',
        selectable: false, evented: false,
      },
      {
        type: 'rect',
        left: 20, top: 20, width: 760, height: 520,
        fill: 'transparent',
        stroke: '#d97706', strokeWidth: 3,
        rx: 4, ry: 4,
        selectable: false, evented: false,
      },
      {
        type: 'rect',
        left: 28, top: 28, width: 744, height: 504,
        fill: 'transparent',
        stroke: 'rgba(217,119,6,0.3)', strokeWidth: 1,
        rx: 2, ry: 2,
        selectable: false, evented: false,
      },
      {
        type: 'text',
        text: '★  CERTIFICATE OF ACHIEVEMENT  ★',
        left: 400, top: 60,
        originX: 'center',
        fontFamily: 'Georgia',
        fontSize: 14,
        fill: '#d97706',
        charSpacing: 40,
        textAlign: 'center',
        fontStyle: 'italic',
      },
      {
        type: 'text',
        text: 'This certifies that',
        left: 400, top: 130,
        originX: 'center',
        fontFamily: 'Georgia',
        fontSize: 15,
        fill: '#92400e',
        textAlign: 'center',
        fontStyle: 'italic',
      },
      {
        type: 'text',
        text: 'RECIPIENT NAME',
        left: 400, top: 170,
        originX: 'center',
        fontFamily: 'Georgia',
        fontSize: 48,
        fill: '#1c1917',
        textAlign: 'center',
        fontStyle: 'italic',
      },
      {
        type: 'line',
        x1: 160, y1: 238, x2: 640, y2: 238,
        stroke: '#d97706', strokeWidth: 1,
      },
      {
        type: 'text',
        text: 'has successfully completed the course of',
        left: 400, top: 255,
        originX: 'center',
        fontFamily: 'Georgia',
        fontSize: 14,
        fill: '#92400e',
        textAlign: 'center',
        fontStyle: 'italic',
      },
      {
        type: 'text',
        text: 'ADVANCED WEB DESIGN',
        left: 400, top: 285,
        originX: 'center',
        fontFamily: 'Georgia',
        fontSize: 28,
        fill: '#d97706',
        textAlign: 'center',
        charSpacing: 30,
        fontWeight: 'bold',
      },
      {
        type: 'text',
        text: 'Date: _____________          Signature: _____________',
        left: 400, top: 440,
        originX: 'center',
        fontFamily: 'Arial',
        fontSize: 12,
        fill: '#6b7280',
        textAlign: 'center',
      },
    ],
  },
  {
    id: 'cert-completion',
    name: 'Completion',
    category: 'certificate',
    width: 800,
    height: 560,
    thumbnail: 'linear-gradient(135deg, #e0e7ff 0%, #c7d2fe 50%, #6366f1 100%)',
    background: '#1e1b4b',
    objects: [
      {
        type: 'rect',
        left: 0, top: 0, width: 800, height: 560,
        fill: '#1e1b4b',
        selectable: false, evented: false,
      },
      {
        type: 'rect',
        left: 30, top: 30, width: 740, height: 500,
        fill: 'transparent',
        stroke: 'rgba(165,180,252,0.3)', strokeWidth: 1,
        selectable: false, evented: false,
      },
      {
        type: 'text',
        text: 'CERTIFICATE',
        left: 400, top: 80,
        originX: 'center',
        fontFamily: 'Impact',
        fontSize: 54,
        fill: '#ffffff',
        charSpacing: 80,
        textAlign: 'center',
      },
      {
        type: 'text',
        text: 'OF COMPLETION',
        left: 400, top: 145,
        originX: 'center',
        fontFamily: 'Arial',
        fontSize: 14,
        fill: '#818cf8',
        charSpacing: 100,
        textAlign: 'center',
      },
      {
        type: 'line',
        x1: 200, y1: 180, x2: 600, y2: 180,
        stroke: 'rgba(129,140,248,0.4)', strokeWidth: 1,
      },
      {
        type: 'text',
        text: 'Proudly presented to',
        left: 400, top: 200,
        originX: 'center',
        fontFamily: 'Georgia',
        fontSize: 14,
        fill: 'rgba(255,255,255,0.6)',
        textAlign: 'center',
        fontStyle: 'italic',
      },
      {
        type: 'text',
        text: 'Your Name Here',
        left: 400, top: 230,
        originX: 'center',
        fontFamily: 'Georgia',
        fontSize: 44,
        fill: '#a5b4fc',
        textAlign: 'center',
        fontStyle: 'italic',
      },
      {
        type: 'text',
        text: 'for outstanding performance in\nDigital Marketing Fundamentals',
        left: 400, top: 310,
        originX: 'center',
        fontFamily: 'Arial',
        fontSize: 14,
        fill: 'rgba(255,255,255,0.7)',
        textAlign: 'center',
        lineHeight: 1.6,
      },
    ],
  },

  // ─────────────── SOCIAL POSTS ───────────────
  {
    id: 'social-quote',
    name: 'Quote Post',
    category: 'social',
    width: 600,
    height: 600,
    thumbnail: 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)',
    background: '#0f172a',
    objects: [
      {
        type: 'rect',
        left: 0, top: 0, width: 600, height: 600,
        fill: '#0f172a',
        selectable: false, evented: false,
      },
      {
        type: 'text',
        text: '"',
        left: 80, top: 80,
        fontFamily: 'Georgia',
        fontSize: 160,
        fill: 'rgba(99,102,241,0.3)',
        lineHeight: 0.6,
      },
      {
        type: 'text',
        text: 'The best way\nto predict\nthe future is\nto create it.',
        left: 80, top: 180,
        fontFamily: 'Georgia',
        fontSize: 36,
        fill: '#ffffff',
        lineHeight: 1.3,
        fontStyle: 'italic',
      },
      {
        type: 'line',
        x1: 80, y1: 490, x2: 180, y2: 490,
        stroke: '#6366f1', strokeWidth: 3,
      },
      {
        type: 'text',
        text: '— PETER DRUCKER',
        left: 196, top: 480,
        fontFamily: 'Arial',
        fontSize: 12,
        fill: '#6366f1',
        charSpacing: 60,
        fontWeight: 'bold',
      },
    ],
  },
  {
    id: 'social-promo',
    name: 'Product Promo',
    category: 'social',
    width: 600,
    height: 600,
    thumbnail: 'linear-gradient(135deg, #134e4a 0%, #0d9488 50%, #2dd4bf 100%)',
    background: '#134e4a',
    objects: [
      {
        type: 'rect',
        left: 0, top: 0, width: 600, height: 600,
        fill: '#134e4a',
        selectable: false, evented: false,
      },
      {
        type: 'rect',
        left: 30, top: 30, width: 540, height: 540,
        fill: 'transparent',
        stroke: 'rgba(45,212,191,0.3)', strokeWidth: 1,
        selectable: false, evented: false,
      },
      {
        type: 'text',
        text: 'NEW\nARRIVAL',
        left: 300, top: 130,
        originX: 'center',
        fontFamily: 'Impact',
        fontSize: 80,
        fill: '#ffffff',
        lineHeight: 0.9,
        textAlign: 'center',
        charSpacing: 20,
      },
      {
        type: 'rect',
        left: 120, top: 320, width: 360, height: 2,
        fill: '#2dd4bf',
      },
      {
        type: 'text',
        text: 'SUMMER 2025 COLLECTION',
        left: 300, top: 340,
        originX: 'center',
        fontFamily: 'Arial',
        fontSize: 13,
        fill: '#2dd4bf',
        charSpacing: 60,
        textAlign: 'center',
      },
      {
        type: 'text',
        text: 'Shop Now →',
        left: 300, top: 490,
        originX: 'center',
        fontFamily: 'Arial',
        fontSize: 16,
        fill: '#ffffff',
        textAlign: 'center',
        fontWeight: 'bold',
      },
    ],
  },
  {
    id: 'social-announcement',
    name: 'Announcement',
    category: 'social',
    width: 600,
    height: 600,
    thumbnail: 'linear-gradient(135deg, #431407 0%, #ea580c 50%, #fed7aa 100%)',
    background: '#431407',
    objects: [
      {
        type: 'rect',
        left: 0, top: 0, width: 600, height: 600,
        fill: '#431407',
        selectable: false, evented: false,
      },
      {
        type: 'text',
        text: '📣',
        left: 300, top: 100,
        originX: 'center',
        fontSize: 64,
        textAlign: 'center',
      },
      {
        type: 'text',
        text: 'BIG\nNEWS!',
        left: 300, top: 190,
        originX: 'center',
        fontFamily: 'Impact',
        fontSize: 96,
        fill: '#fed7aa',
        lineHeight: 0.85,
        textAlign: 'center',
        charSpacing: 30,
      },
      {
        type: 'text',
        text: 'Something exciting is\ncoming your way.',
        left: 300, top: 400,
        originX: 'center',
        fontFamily: 'Georgia',
        fontSize: 20,
        fill: 'rgba(254,215,170,0.8)',
        textAlign: 'center',
        lineHeight: 1.6,
        fontStyle: 'italic',
      },
      {
        type: 'text',
        text: 'STAY TUNED',
        left: 300, top: 510,
        originX: 'center',
        fontFamily: 'Arial',
        fontSize: 13,
        fill: '#ea580c',
        charSpacing: 100,
        textAlign: 'center',
        fontWeight: 'bold',
      },
    ],
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'flyer', label: 'Flyers' },
  { id: 'logo', label: 'Logos' },
  { id: 'certificate', label: 'Certificates' },
  { id: 'social', label: 'Social' },
] as const;

export function getTemplatesByCategory(category: string) {
  if (category === 'all') return TEMPLATES;
  return TEMPLATES.filter(t => t.category === category);
}
